#!/bin/sh

# This script compiles and and upload arduino code for arduino uno (TODO: more boards to come, user specified port)
# This script should be run under the sketch folder
arduino-cli --config-file $XDG_CONFIG_HOME/arduino/arduino-cli.yaml compile -b arduino:avr:uno -v
arduino-cli --config-file $XDG_CONFIG_HOME/arduino/arduino-cli.yaml upload -b arduino:avr:uno -p /dev/ttyACM0 -v $1
