#!/bin/sh

# Adjust the brightness of the laptop screen
# change screen path for other laptops

dir="/sys/class/backlight/$(ls /sys/class/backlight)"
max_brightness=$(cat $dir/max_brightness)
current_brightness=$(cat $dir/brightness)
step=$(($max_brightness/100))

[ "$#" -gt 2 -o "$1" == "-h" -o "$1" == "--help" ] && {
    echo -e "Usage:\n\t$ brightness [-i] [-d] [step level]"
    exit 1
}

[ "$#" -eq 2 ] && step=$("$1")

if [ "$1" == "-i" ]; then
    brightness=$(($current_brightness+$step))
elif [ "$1" == "-d" ]; then
    brightness=$(($current_brightness-$step))
else
    echo -e "Invalid arguments, use -h for help."
    exit 1
fi

[ $brightness -gt $max_brightness -o $brightness -lt $(($max_brightness/10)) ] || echo $brightness > "$dir/brightness"

