#!/bin/sh

# Show time/date, volume and other status on dwm bar
# TODO: kill the sleep 1 process every time any status (eg:volume) changes

while true; do
	date=$(date +"%a %d/%m/%Y")
	time=$(date +"%I:%M:%S %P")
	volume=$(pamixer --get-volume-human)  
	current_layout=$(xkb-switch)
	xsetroot -name " $current_layout | Vol:$volume | $time | $date"
	sleep 1
done

