#!/bin/sh

# Enables/Disables touchpad in laptops using xinput

id=$(xinput list | grep -i "touchpad" | awk '{print $7}' | cut -d "=" -f 2)
enabled=$(xinput list-props 14 | grep "Device Enabled" | awk '{print $4}')

[ $enabled -eq "1" ] && xinput disable "$id" || xinput enable "$id"

