#!/bin/sh

# Variables defined on torrent finish (github wiki):
# * TR_APP_VERSION
# * TR_TIME_LOCALTIME
# * TR_TORRENT_DIR
# * TR_TORRENT_HASH
# * TR_TORRENT_ID
# * TR_TORRENT_NAME

# Notification script for transmission-daemon
notify-send "Transmission Daemon" "$TR_TORRENT_NAME has completely downloaded!"
